name: Calibre

on:
  workflow_dispatch:
    inputs:
      urlinput:
        description: Url input file
        required: true
      extinput:
        description: Extension of input file
        required: true
      extoutput:
        description: Extension of output file
        required: true
      option:
        description: Options
        required: false

jobs:
  calibre-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Calibre and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre xvfb curl

      - name: Download input
        run: |
          curl --location ${{ github.event.inputs.urlinput }} --output curl.${{ github.event.inputs.extinput }}

      - name: Execute Calibre Commands
        run: |
          # xvfb-run provides the virtual display server Calibre requires
          xvfb-run ebook-convert curl.${{ github.event.inputs.extinput }} out.${{ github.event.inputs.extoutput }} ${{ github.event.inputs.option }}

      - name: Upload output
        run: |
          curl -i -F files[]=@out.${{ github.event.inputs.extoutput }} https://uguu.se/upload?output=text
